add validation in value object
mexanicS/PetHelper pull request #10
Opened 2024-09-24 15:53 UTC by mexanicS

2024-09-24 18:20 UTC, YaraOduvanchik requested changes
Добавь валидацию для доменных моделей, в задании об этом указано (если модель полностью состоит из ValueObjects, то можно сделать публичный конструктор, так как ValueObjects уже провалидированные)

2024-09-24 18:20 UTC, YaraOduvanchik commented on PetHelper.Backend/src/PetHelper.Domain/Models/Pet/Pet.cs
> +        public Name Name { get; private set; } = null!;
Для доменных моделей тоже нужно доабвлять валидацию

2024-09-25 12:09 UTC, mexanicS commented
Правильно ли я понял что у нас вся валидация в VO в методах Create, поэтому мы можем сделать конструктор публичным для Pet Volunteer Species Breed

2024-09-25 12:51 UTC, YaraOduvanchik commented
> Правильно ли я понял что у нас вся валидация в VO в методах Create, поэтому мы можем сделать конструктор публичным для Pet Volunteer Species Breed

Да, ты правильно понял

2024-09-25 12:53 UTC, YaraOduvanchik approved these changes

2024-09-25 13:18 UTC, merged