add create species and breed
mexanicS/PetHelper pull request #17
Opened 2024-10-04 19:18 UTC by mexanicS

2024-10-04 19:18 UTC, mexanicS commented
особенно интересует реализация в AddBreedHandler

2024-10-05 03:03 UTC, YaraOduvanchik requested changes

2024-10-05 03:03 UTC, n-cherashev commented on PetHelper.Backend/src/PetHelper.API/Controllers/SpeciesController.cs
> +    [HttpPost("/breed")]
Мы должны добавлять Breed через Species, так как это агрегат

Соответственно нам нужно получть id species, в которую мы будем добавлять породы: [HttpPost("{speciesId:guid}/issue")]

2024-10-05 03:03 UTC, n-cherashev commented on PetHelper.Backend/src/PetHelper.API/Controllers/SpeciesController.cs
> +        [FromServices] AddBreedHandler handler,
Id мы всегда получаем из параметров, вот так:
[FromRoute] Guid id

2024-10-05 03:03 UTC, n-cherashev commented on PetHelper.Backend/src/PetHelper.API/Controllers/SpeciesController.cs
> +        [FromBody] AddBreedRequest request,
тут можно сделать AddBreedDto например

2024-10-05 03:03 UTC, YaraOduvanchik commented on PetHelper.Backend/src/PetHelper.API/Controllers/SpeciesController.cs
> +    {
А тут можно создавать request из id и dto

Нужно ещё в параметрах принимать IValidator<AddBreedRequest> и валидировать request, который создаётся в методе, потому что для таких request не работает автовалидация

2024-10-07 04:42 UTC, YaraOduvanchik approved these changes

2024-10-07 04:50 UTC, merged