add controller
mexanicS/PetHelper pull request #9
Opened 2024-09-19 19:18 UTC by mexanicS

2024-09-20 08:46 UTC, KirillSachkov requested changes

2024-09-20 08:46 UTC, KirillSachkov commented on PetHelper.Backend/src/PetHelper.Application/Volunteers/CreateVolunteers/CreateVolunteerHandler.cs
> +            ).DetailsForAssistances);
Вот это всё можно вынести в отдельный приватный метод для красоты

2024-09-20 08:46 UTC, KirillSachkov commented on PetHelper.Backend/src/PetHelper.Domain/ValueObjects/DetailsForAssistanceList.cs
> +    public IReadOnlyList<DetailsForAssistance> DetailsForAssistances { get; } = [];
Здесь не стоит делать инициализацю, ef core будет ругаться, потому что это json. В дальнейшем мы это пофиксили

2024-09-20 08:46 UTC, KirillSachkov commented on PetHelper.Backend/src/PetHelper.Domain/ValueObjects/DetailsForAssistanceList.cs
> +    public static DetailsForAssistanceList Create(IEnumerable<DetailsForAssistance> detailsForAssistance) => new DetailsForAssistanceList();
Этот метод бесплезный, если нет никаких проверок или ещё чего-то, то лучше просто использовать публичный конструктор

2024-09-20 08:46 UTC, KirillSachkov commented on PetHelper.Backend/src/PetHelper.Domain/ValueObjects/DetailsForAssistanceList.cs
> +    public static DetailsForAssistanceList Create(IEnumerable<DetailsForAssistance> detailsForAssistance) => new DetailsForAssistanceList();
Везде стоит придерживаться такой логики

2024-09-20 08:46 UTC, KirillSachkov commented on PetHelper.Backend/src/PetHelper.Domain/ValueObjects/VolunteerDetails.cs
> +        private VolunteerDetails(
Лучше убрать такой VO и для каждого списка создавать свою обертку, не стоит складывать всё в одно место

2024-09-23 07:20 UTC, mexanicS commented
не слишком сильно разбил на методы в CreateVolunteerHandler?

2024-09-23 17:35 UTC, KirillSachkov requested changes
Слишком сильно разбил на методы, я имел в виду, чтобы ты вынес всё создание экземпляра волонтер. Нет смысла под создание каждого поля выделять отдельным метод

2024-09-23 17:55 UTC, KirillSachkov approved these changes

2024-09-24 09:20 UTC, KirillSachkov approved these changes

2024-09-24 09:42 UTC, merged